# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "79b63db0f617a13cadd8d3ffd7d52013"
name = "Sales Pilot"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_orders,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
